#!/usr/bin/env bash
# Writes scripts/.env for your Neon database.
#
# Paste EITHER just the password, OR the whole connection string -- the script
# works out which one you gave it. Input is never echoed, never stored in shell
# history, and the password is percent-encoded before it goes into the URI so
# special characters cannot break the parse.
set -euo pipefail
cd "$(dirname "$0")/.."

if ! command -v psql >/dev/null 2>&1; then
  for d in /opt/homebrew/opt/libpq/bin /usr/local/opt/libpq/bin; do
    [ -x "$d/psql" ] && export PATH="$d:$PATH" && break
  done
fi

# Defaults, used only when you paste a bare password.
export NEON_DEFAULT_HOST="${NEON_DEFAULT_HOST:-ep-xxxx.REGION.aws.neon.tech}"
export NEON_DEFAULT_DB="neondb"
export NEON_DEFAULT_USER="neondb_owner"

printf 'Paste your Neon password OR the full connection string (input hidden): '
read -rs NEON_INPUT
printf '\n'
export NEON_INPUT
[ -n "$NEON_INPUT" ] || { echo "nothing entered, aborting" >&2; exit 1; }

python3 - <<'PY'
import os, sys, re
from urllib.parse import urlsplit, quote, unquote

raw  = os.environ["NEON_INPUT"].strip().strip('"').strip("'")
host = os.environ["NEON_DEFAULT_HOST"]
db   = os.environ["NEON_DEFAULT_DB"]
user = os.environ["NEON_DEFAULT_USER"]

if "://" in raw:
    # A full connection string. Take everything from it.
    parts = urlsplit(raw)
    if not parts.password:
        sys.exit("that connection string has no password in it -- click "
                 "'Show password' in Neon first, then copy it again")
    user = unquote(parts.username or user)
    pwd  = unquote(parts.password)
    host = parts.hostname or host
    db   = (parts.path or "/" + db).lstrip("/") or db
else:
    pwd = raw

if "@" in host or "/" in host:
    sys.exit("could not make sense of the host -- re-copy from Neon and retry")

# Neon's pooled endpoint is the direct one with -pooler after the endpoint id.
direct = host.replace("-pooler", "")
labels = direct.split(".")
labels[0] = labels[0] + "-pooler"
pooled = ".".join(labels)

enc = quote(pwd, safe="")

with open("scripts/.env", "w") as f:
    f.write(f"""# Generated by scripts/set_password.sh -- gitignored, never commit.
# Neon project: olist-analytics

# Direct endpoint -- use for the bulk CSV load (COPY through a pooler is slower
# and more likely to time out).
DATABASE_URL="postgresql://{user}:{enc}@{direct}/{db}?sslmode=require"

# Pooled endpoint -- use for n8n and Power BI, which open many short connections.
DATABASE_URL_POOLED="postgresql://{user}:{enc}@{pooled}/{db}?sslmode=require"

DATA_DIR="./data"
""")

print(f"wrote scripts/.env")
print(f"  user     {user}")
print(f"  host     {direct}")
print(f"  pooled   {pooled}")
print(f"  database {db}")
print(f"  password {len(pwd)} chars" + (" (percent-encoded)" if enc != pwd else ""))
PY

chmod 600 scripts/.env
unset NEON_INPUT

echo
echo ">> testing the direct endpoint"
set -a && . scripts/.env && set +a
psql "$DATABASE_URL" -Atc "SELECT 'OK: ' || current_database() || ' as ' || current_user;"

echo ">> testing the pooled endpoint"
psql "$DATABASE_URL_POOLED" -Atc "SELECT 'OK: pooled endpoint reachable';"
