-- =============================================================================
-- 05_dimensions.sql
-- Star schema dimensions.
--
-- Key policy: Olist's natural keys are already opaque 32-character hashes, so
-- generating integer surrogates would add a join without adding meaning -- and
-- surrogates generated by a VIEW would renumber themselves on every refresh.
-- The natural keys are used directly as relationship columns.
--
-- The one non-obvious modelling decision in this whole project:
--   customer_id in Olist is issued PER ORDER. customer_unique_id is the person.
--   Every customer-level view below keys on customer_unique_id. Getting this
--   wrong makes the repeat-purchase rate come out as 0% and quietly ruins RFM,
--   cohort and LTV -- it is the single most common mistake in Olist projects.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- dim_customer : one row per real person.
-- Attributes are taken from the person's MOST RECENT order (people move).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.dim_customer AS
WITH cust_orders AS (
    -- every order, valid or not -- attributes like city are known regardless
    SELECT
        c.customer_unique_id,
        c.customer_id,
        c.city,
        c.state_code,
        c.zip_code_prefix,
        o.purchase_date,
        row_number() OVER (PARTITION BY c.customer_unique_id
                           ORDER BY o.purchase_date DESC, o.order_id DESC) AS rn_latest
    FROM stg.customers c
    JOIN stg.orders    o ON o.customer_id = c.customer_id
),
agg AS (
    -- counts and dates over VALID orders only. A cancelled order is not a
    -- purchase, so it must not make someone a "repeat customer" here while
    -- vw_customer_ltv (which filters the same way) shows them with one order.
    SELECT
        c.customer_unique_id,
        min(o.purchase_date) AS first_order_date,
        max(o.purchase_date) AS last_order_date,
        count(*)             AS lifetime_orders
    FROM stg.customers c
    JOIN stg.orders    o ON o.customer_id = c.customer_id
    WHERE o.order_status NOT IN ('canceled','unavailable')
    GROUP BY c.customer_unique_id
)
SELECT
    l.customer_unique_id,
    l.city                                          AS customer_city,
    l.state_code                                    AS customer_state_code,
    s.state_name                                    AS customer_state,
    s.region                                        AS customer_region,
    l.zip_code_prefix                               AS customer_zip_prefix,
    a.first_order_date,
    a.last_order_date,
    date_trunc('month', a.first_order_date)::date   AS cohort_month,
    to_char(a.first_order_date, 'Mon YYYY')         AS cohort_month_label,
    to_char(a.first_order_date, 'YYYYMM')::int      AS cohort_month_key,
    coalesce(a.lifetime_orders, 0)                  AS lifetime_orders,
    (coalesce(a.lifetime_orders, 0) > 1)            AS is_repeat_customer
-- LEFT JOIN, not INNER: a customer whose only order was cancelled still exists
-- and still owns fact rows. Dropping them here would orphan those rows.
FROM cust_orders l
LEFT JOIN agg        a ON a.customer_unique_id = l.customer_unique_id
LEFT JOIN stg.br_state s ON s.state_code = l.state_code
WHERE l.rn_latest = 1;

-- -----------------------------------------------------------------------------
-- dim_product
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.dim_product AS
SELECT
    p.product_id,
    p.category_key,
    p.category_en                                   AS category,
    p.category_group,
    p.category_pt                                   AS category_portuguese,
    p.photos_qty,
    p.name_length,
    p.description_length,
    p.weight_g,
    round(p.weight_g / 1000.0, 3)                   AS weight_kg,
    p.length_cm, p.height_cm, p.width_cm,
    p.volume_cm3,
    CASE
        WHEN p.weight_g IS NULL      THEN 'Unknown'
        WHEN p.weight_g <    500     THEN '1. Under 0.5kg'
        WHEN p.weight_g <   2000     THEN '2. 0.5-2kg'
        WHEN p.weight_g <  10000     THEN '3. 2-10kg'
        ELSE                              '4. Over 10kg'
    END                                             AS weight_band,
    CASE
        WHEN p.photos_qty = 0 THEN 'No photo'
        WHEN p.photos_qty = 1 THEN '1 photo'
        WHEN p.photos_qty <= 3 THEN '2-3 photos'
        ELSE '4+ photos'
    END                                             AS photo_band
FROM stg.products p;

-- -----------------------------------------------------------------------------
-- dim_seller
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.dim_seller AS
SELECT
    s.seller_id,
    s.city                                          AS seller_city,
    s.state_code                                    AS seller_state_code,
    b.state_name                                    AS seller_state,
    b.region                                        AS seller_region
FROM stg.sellers s
LEFT JOIN stg.br_state b ON b.state_code = s.state_code;

-- -----------------------------------------------------------------------------
-- dim_geo : one row per state. This is the RLS dimension -- security filters
-- applied here propagate down to fact_sales through customer_state_code.
-- Centroid comes from the zip-prefix geolocation samples, weighted by how many
-- samples each prefix contributed, so it lands on the populated part of the
-- state rather than its geometric middle.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.dim_geo AS
WITH centroid AS (
    SELECT
        g.state_code,
        round(sum(g.lat * g.sample_count) / nullif(sum(g.sample_count), 0), 6) AS lat,
        round(sum(g.lng * g.sample_count) / nullif(sum(g.sample_count), 0), 6) AS lng
    FROM stg.geolocation g
    GROUP BY g.state_code
)
SELECT
    b.state_code,
    b.state_name,
    b.region,
    b.state_name || ', Brazil'                      AS map_location,
    'Brazil'                                        AS country,
    c.lat                                           AS latitude,
    c.lng                                           AS longitude
FROM stg.br_state b
LEFT JOIN centroid c ON c.state_code = b.state_code;

-- -----------------------------------------------------------------------------
-- dim_payment_type
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW mart.dim_payment_type AS
SELECT * FROM (VALUES
    ('credit_card', 'Credit card', 1),
    ('boleto',      'Boleto',      2),
    ('voucher',     'Voucher',     3),
    ('debit_card',  'Debit card',  4)
) AS t(payment_type, payment_type_label, sort_order);

COMMENT ON VIEW mart.dim_payment_type IS
    'Boleto is a Brazilian bank slip -- pay-on-print, no card needed. It is ~20% of orders and behaves nothing like a card payment, which is why payment type earns its own dimension.';
